doctor-config:
    specializations:
      - 'Surgeon'
      - 'Dentist'
      - 'Psychologist'

spring:
  datasource:
      url: jdbc:mysql://localhost/doctors_clinic
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: root

  jackson:
    serialization:
      write_dates_as_timestamps: false
      indent-output: true
  jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate:
        ddl-auto: create
      open-in-view: false

