doctor-config:
    specializations:
      - 'Surgeon'
      - 'Dentist'
      - 'Psychologist'

spring:
    profiles: postgre
    datasource:
        url: jdbc:postgresql:doctors_clinic
        username: postgres
        password: root

    jackson:
      #property-naming-strategy: SNAKE_CASE
      serialization:
        write_dates_as_timestamps: false
        indent-output: true
    jpa:
        #show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: create
        open-in-view: false
---

spring:
  #profiles: mysql
  datasource:
      url: jdbc:mysql://localhost/doctors
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: root

  jackson:
    serialization:
      write_dates_as_timestamps: false
      indent-output: true
  jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate:
        ddl-auto: update
      open-in-view: false

